from django.contrib import admin
from django.urls import path
import gkapp.views as views

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('get-room-categories/<int:guesthouse_id>/', views.get_room_categories, name='get_room_categories'),
    path('get-guest-categories/<int:room_category_id>/', views.get_guest_categories, name='get_guest_categories'),
    path('customer/login', views.customer_login, name="customer_login"),
    path('customer/signup', views.customer_signup.as_view(), name="customer_signup"),
    path('customer/customer_dash', views.customer_dash, name="customer_dash"),
    path('customer/request', views.request, name="request"),
    path('employee/approval', views.approval, name="approval"),
    path('employee/login', views.employee_login, name="employee_login"),
    path('employee/signup', views.employee_signup.as_view(), name="employee_signup"),
    path('employee/employee_dash', views.employee_dash, name="employee_dash"),
    path('employee/guesthouseshw', views.guesthouseshw, name="guesthouseshw"),
    path('employee/roomrates', views.roomrates, name="roomrates"),
    path('employee/addguesthouse', views.addguesthouse, name="addguesthouse"),
    path('employee/viewroomcategories', views.viewroomcategories, name="viewroomcategories"),
    path('employee/addroomcategories', views.addroomcategories, name="addroomcategories"),
    path('employee/viewguestcategories', views.viewguestcategories, name="viewguestcategories"),
    path('employee/addguestcategories', views.addguestcategories, name="addguestcategories"),
    path('employee/viewroomrates', views.viewroomrates, name="viewroomrates"),
    path('employee/addroomrates', views.addroomrates, name="addroomrates"),
    path('employee/viewrooms', views.viewrooms, name="viewrooms"),
    path('employee/addrooms', views.addrooms, name="addrooms"),
    path('employee/addbooking', views.addbooking, name="addbooking"),
    path('employee/viewbooking', views.viewbooking, name="viewbooking"),
    path('logout/',views.logout_view, name='logout'),
    path('employee/requestshow',views.show, name='show'),
    path('admin/', admin.site.urls),
    path('employee/rr', views.create_room_rate, name='create_room_rate'),
    path('booking_procedure', views.booking_procedure, name='booking_procedure'),
    path('images', views.images, name='images'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('committee', views.committee, name='committee'),
    path('imp_info', views.imp_info, name='imp_info'),
]