# Generated by Django 4.1.7 on 2023-10-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mob', models.IntegerField(null=True)),
                ('id_proof_no', models.IntegerField(null=True)),
                ('no_of_persons', models.IntegerField(null=True)),
                ('no_of_rooms', models.IntegerField(null=True)),
                ('checkin', models.DateTimeField(auto_now=True)),
                ('checkout', models.DateTimeField(auto_now=True)),
                ('request_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
