# Generated by Django 4.1.7 on 2023-10-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0003_alter_request_checkin_alter_request_checkout_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrates',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
